### ISSUE TITLE
AttributeError: module 'utils' has no attribute 'get_platform'

### ISSUE THREAD

**Issue by xenakes** [sdushantha/wifi-password#100]
Mac OS Sonoma 14.2.1
Python3 3.11.5

Get the following error when trying to use..

wifi-password
Traceback (most recent call last):
  File "/Users/racerx/anaconda3/bin/wifi-password", line 33, in <module>
    sys.exit(load_entry_point('wifi-password==1.1.1', 'console_scripts', 'wifi-password')())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/racerx/anaconda3/lib/python3.11/site-packages/wifi_password-1.1.1-py3.11.egg/wifi_password/wifi_password.py", line 99, in main
  File "/Users/racerx/anaconda3/lib/python3.11/site-packages/wifi_password-1.1.1-py3.11.egg/wifi_password/wifi_password.py", line 33, in get_ssid
AttributeError: module 'utils' has no attribute 'get_platform'

**Comment by Muxutruk2** [comment]
Have you installed "utils" as in "https://pypi.org/project/utils/" ?

**Comment by toddyhan** [comment]
> Mac OS Sonoma 14.2.1 Python3 3.11.5
> 
> Get the following error when trying to use..
> 
> wifi-password Traceback (most recent call last): File "/Users/racerx/anaconda3/bin/wifi-password", line 33, in sys.exit(load_entry_point('wifi-password==1.1.1', 'console_scripts', 'wifi-password')()) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/Users/racerx/anaconda3/lib/python3.11/site-packages/wifi_password-1.1.1-py3.11.egg/wifi_password/wifi_password.py", line 99, in main File "/Users/racerx/anaconda3/lib/python3.11/site-packages/wifi_password-1.1.1-py3.11.egg/wifi_password/wifi_password.py", line 33, in get_ssid AttributeError: module 'utils' has no attribute 'get_platform'



goto file wifi_password/wifi_password.py, modify this import:
```
#import utils
from . import utils
#import constants
from . import constants
```

if getting other errors for local module, modify like this.
