### ISSUE TITLE
Error when saving QR Code

### ISSUE THREAD

**Issue by jiayounokim** [sdushantha/wifi-password#51]
```
Traceback (most recent call last):
  File "C:\Users\username\AppData\Local\Programs\Python\Python39\Scripts\wifi-password-script.py", line 33, in <module>
    sys.exit(load_entry_point('wifi-password==1.1.1', 'console_scripts', 'wifi-password')())
  File "C:\Users\username\AppData\Local\Programs\Python\Python39\lib\site-packages\wifi_password-1.1.1-py3.9.egg\wifi_password\wifi_password.py", line 165, in main
  File "C:\Users\username\AppData\Local\Programs\Python\Python39\lib\site-packages\wifi_password-1.1.1-py3.9.egg\wifi_password\wifi_password.py", line 126, in generate_qr_code
  File "C:\Users\username\AppData\Roaming\Python\Python39\site-packages\qrcode\image\pil.py", line 50, in save
    self._img.save(stream, format=format, **kwargs)
  File "C:\Users\username\AppData\Roaming\Python\Python39\site-packages\PIL\Image.py", line 2161, in save
    fp = builtins.open(filename, "w+b")
OSError: [Errno 22] Invalid argument: 'Name\r.png'h

```

**Comment by sdushantha** [comment]
@donenoyes This seems odd. I'm not sure why there is a `\r` character. Is the name of your SSID `Name`?
